name: l2struc_python
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip=20.2.4
  - pandas=1.1.3
  - numpy=1.19.5
  - jupyterlab=3.0.8
  - matplotlib=3.3.4
  - pip:
    - pydicom==2.1.2
    - tensorflow==2.4.1
    - scikit-learn==0.24.1